#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "filebrowser-quantum"
name = "FileBrowser Quantum"
description.en = "Web File Browser"
description.fr = "Navigateur de fichiers Web"

version = "1.5.3~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "Apache-2.0"
admindoc = "https://filebrowserquantum.com/en/docs/getting-started/linux/"
code = "https://github.com/gtsteffaniak/filebrowser"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true

ldap = false
sso = false

disk = "100M"
ram.build = "100M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    rename = "filebrowser"
    extract = false
    amd64.url = "https://github.com/gtsteffaniak/filebrowser/releases/download/v1.5.3-stable/linux-amd64-filebrowser"
    amd64.sha256 = "cb7ddce34fefc5f5682c986a8536ff09ec9dafea1f1bc0456ea86219eb9023a5"
    arm64.url = "https://github.com/gtsteffaniak/filebrowser/releases/download/v1.5.3-stable/linux-arm64-filebrowser"
    arm64.sha256 = "a62c3fd586456fdee16fb44c7697425c5e231f69a00d1382de7e2615076cbb1f"
    armhf.url = "https://github.com/gtsteffaniak/filebrowser/releases/download/v1.5.3-stable/linux-armv7-filebrowser"
    armhf.sha256 = "470673b9d408bf3c66e159f039a49e0b4baf003d4ba37b5e20a4bc0ceda7e6f7"
    autoupdate.strategy = "latest_github_release"
    autoupdate.version_regex = "v(\\d+\\.\\d+\\.\\d+)-stable"
    autoupdate.asset.amd64 = "linux-amd64-filebrowser"
    autoupdate.asset.arm64 = "linux-arm64-filebrowser"
    autoupdate.asset.armhf = "linux-armv7-filebrowser"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "ffmpeg"
