#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "filebrowser-quantum"
name = "FileBrowser Quantum"
description.en = "Web File Browser"
description.fr = "Navigateur de fichiers Web"

version = "1.5.2~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "Apache-2.0"
admindoc = "https://filebrowserquantum.com/en/docs/getting-started/linux/"
code = "https://github.com/gtsteffaniak/filebrowser"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true

ldap = false
sso = false

disk = "100M"
ram.build = "100M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    rename = "filebrowser"
    extract = false
    amd64.url = "https://github.com/gtsteffaniak/filebrowser/releases/download/v1.5.2-stable/linux-amd64-filebrowser"
    amd64.sha256 = "2cc7c2e39fc24831578fdb4da02c5dfeb39669203fc8c6d6bfbbfa35577f5173"
    arm64.url = "https://github.com/gtsteffaniak/filebrowser/releases/download/v1.5.2-stable/linux-arm64-filebrowser"
    arm64.sha256 = "5194e8cca5c74705afbd9696dda7d0279ddaf9d04c3c39f18f956d646ada3b64"
    armhf.url = "https://github.com/gtsteffaniak/filebrowser/releases/download/v1.5.2-stable/linux-armv7-filebrowser"
    armhf.sha256 = "7bbcb917eaaabe2d94f920b851844049ecc9450e1280a076ddf95da32e196e76"
    autoupdate.strategy = "latest_github_release"
    autoupdate.version_regex = "v(\\d+\\.\\d+\\.\\d+)-stable"
    autoupdate.asset.amd64 = "linux-amd64-filebrowser"
    autoupdate.asset.arm64 = "linux-arm64-filebrowser"
    autoupdate.asset.armhf = "linux-armv7-filebrowser"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "ffmpeg"
