#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "filebrowser-quantum"
name = "FileBrowser Quantum"
description.en = "Web File Browser"
description.fr = "Navigateur de fichiers Web"

version = "1.4.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "Apache-2.0"
admindoc = "https://filebrowserquantum.com/en/docs/getting-started/linux/"
code = "https://github.com/gtsteffaniak/filebrowser"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true

ldap = false
sso = false

disk = "100M"
ram.build = "100M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    rename = "filebrowser"
    extract = false
    amd64.url = "https://github.com/gtsteffaniak/filebrowser/releases/download/v1.4.0-stable/linux-amd64-filebrowser"
    amd64.sha256 = "f104afa1398a9daf629113d5250951159e389837624b6924abc6e8ca845c62ac"
    arm64.url = "https://github.com/gtsteffaniak/filebrowser/releases/download/v1.4.0-stable/linux-arm64-filebrowser"
    arm64.sha256 = "12b3ea8ff81fda0ef1390221d477f40803b2b501c86ad4c9f885020a30fa8841"
    armhf.url = "https://github.com/gtsteffaniak/filebrowser/releases/download/v1.4.0-stable/linux-armv7-filebrowser"
    armhf.sha256 = "0c830749b2e7e8083246531748e86d6648f070903a2c24e5f41dbae617f1579f"
    autoupdate.strategy = "latest_github_release"
    autoupdate.version_regex = "v(\\d+\\.\\d+\\.\\d+)-stable"
    autoupdate.asset.amd64 = "linux-amd64-filebrowser"
    autoupdate.asset.arm64 = "linux-arm64-filebrowser"
    autoupdate.asset.armhf = "linux-armv7-filebrowser"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "ffmpeg"
