#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="config.yaml"

chmod +x "$install_dir/filebrowser"

#=================================================
# UPDATE A CONFIG FILE
#=================================================

if ynh_app_upgrading_from_version_before_or_equal_to 1.4.0~ynh1; then
  ynh_script_progression "Updating $app's configuration files..."
  ynh_replace --match="indexingIntervalMinutes:" --replace="#indexingIntervalMinutes:" --file="$install_dir/config.yaml"
  ynh_replace --match="disableIndexing:" --replace="#disableIndexing:" --file="$install_dir/config.yaml"
  ynh_store_file_checksum "$install_dir/config.yaml"
fi

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Web File Browser" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
